const {test}=require('node:test');
const a=require('node:assert/strict');
const {makeSeed}=require('../.test-build/src/data/seed.js');
const {applyCommand}=require('../.test-build/src/domain/engine.js');
const {parseState,parseBackup,parseOrder,iso}=require('../.test-build/src/domain/validation.js');
const {assessCancellation,draftReply,isOverdue}=require('../.test-build/src/domain/rules.js');
const {metrics,dailySeries}=require('../.test-build/src/domain/metrics.js');
const {parseCSV,previewCSV,toCSV,sampleCSV}=require('../.test-build/src/lib/csv.js');
const {LocalRepository,STORAGE_KEY}=require('../.test-build/src/lib/repository.js');
const time='2026-09-29T03:00:00.000Z';let serial=0;
const rt={now:()=>time,id:p=>`${p}-test-${++serial}`};
const agent={role:'agent',name:'상담원'},manager={role:'manager',name:'관리자'};
const seed=()=>makeSeed(new Date(time));
const run=(s,c,actor=agent)=>applyCommand(s,c,actor,rt);
const req=s=>run(s,{type:'approval.request',ticketId:'T-2001',reason:'고객이 취소 요청'});
const approve=s=>run(s,{type:'approval.decide',id:s.approvals[0].id,decision:'approved',reason:'출고 전 상태 확인'},manager);
const execute=s=>run(s,{type:'approval.execute',id:s.approvals[0].id},manager);
const ship=s=>run(s,{type:'order.logistics',id:'ORD-1001',status:'shipped',carrier:'가상택배',tracking:'DEMO-TRACK'},manager);
const policy=s=>run(s,{type:'policy.update',policy:{...s.policy,shippingNote:'변경한 연습 정책'}},manager);
const reply=(s,id='T-2001')=>run(run(s,{type:'ticket.draft',id}),{type:'ticket.send',id});
function memory(raw=null){let value=raw;return{getItem:()=>value,setItem:(k,v)=>{value=v},removeItem:()=>{value=null}}}

test('seed is a valid, isolated schema with 12 fake orders and tickets',()=>{const s=seed();a.equal(parseState(s).orders.length,12);a.equal(s.tickets.length,12);a.ok(s.orders.every(o=>o.email.endsWith('@example.com')));});
test('successful command is immutable and increments revision plus audit',()=>{const s=seed();const n=run(s,{type:'ticket.note',id:'T-2001',body:'메모'});a.equal(s.tickets[0].notes.length,0);a.equal(n.revision,1);a.equal(n.events[0].kind,'ticket.note');parseState(n)});
test('invalid command is rejected instead of silently creating an audit',()=>a.throws(()=>run(seed(),{type:'unknown'}),/지원하지/));
test('full cancellation request -> approval -> simulated execution -> reply -> resolution',()=>{let s=req(seed());a.equal(s.tickets[0].status,'waiting_approval');a.equal(s.orders[0].status,'preparing');s=approve(s);a.equal(s.orders[0].status,'preparing');s=execute(s);a.equal(s.orders[0].status,'cancelled');a.equal(s.orders[0].amount,49000);a.equal(s.approvals[0].status,'executed');a.match(s.events[0].detail,/실제 주문\/결제\/환불은 변경하지 않음/);s=reply(s);s=run(s,{type:'ticket.resolve',id:'T-2001'});a.equal(s.tickets[0].status,'resolved');parseState(s);});
test('same order cannot have overlapping active approval',()=>{const s=req(seed());a.throws(()=>req(s),/이미 진행/);a.equal(s.approvals.length,1)});
test('agent cannot approve a request',()=>{const s=req(seed());a.throws(()=>run(s,{type:'approval.decide',id:s.approvals[0].id,decision:'approved',reason:'승인'}),/관리자/)});
test('agent cannot execute approved cancellation',()=>{const s=approve(req(seed()));a.throws(()=>run(s,{type:'approval.execute',id:s.approvals[0].id}),/관리자/)});
test('pending cancellation cannot execute',()=>a.throws(()=>execute(req(seed())),/승인된/));
test('executed cancellation cannot execute twice',()=>{const s=execute(approve(req(seed())));a.throws(()=>execute(s),/재실행/);a.equal(s.orders[0].version,2)});
test('shipping after approval blocks execution without cancelling order',()=>{const s=execute(ship(approve(req(seed()))));a.equal(s.approvals[0].status,'blocked');a.equal(s.orders[0].status,'shipped');a.equal(s.tickets[0].status,'escalated');parseState(s)});
test('policy change before approval blocks stale request',()=>{const s=approve(policy(req(seed())));a.equal(s.approvals[0].status,'blocked');parseState(s)});
test('policy change after approval blocks execution',()=>a.equal(execute(policy(approve(req(seed())))).approvals[0].status,'blocked'));
test('rejection is explicit and does not cancel order',()=>{let s=req(seed());s=run(s,{type:'approval.decide',id:s.approvals[0].id,decision:'rejected',reason:'추가 확인 필요'},manager);a.equal(s.approvals[0].status,'rejected');a.equal(s.orders[0].status,'preparing');parseState(s)});
test('request cannot be approved twice',()=>a.throws(()=>approve(approve(req(seed()))),/검토 대기/));
test('high amount cancellation fails policy',()=>a.throws(()=>run(seed(),{type:'approval.request',ticketId:'T-2006',reason:'취소'})));
test('shipped order cannot be approved for pre-shipment cancellation',()=>a.equal(assessCancellation(ship(seed()),ship(seed()).tickets[0]).allowed,false));
test('inquiry type must be cancellation',()=>a.equal(assessCancellation(seed(),seed().tickets[2]).allowed,false));
test('missing order denies cancellation and draft asks for identification',()=>{const s=seed();s.tickets[0].orderId='MISSING';a.equal(assessCancellation(s,s.tickets[0]).allowed,false);a.ok(draftReply(s,s.tickets[0]).length>0)});
test('mismatched email blocks cancellation and draft hides item and amount',()=>{const s=seed();s.tickets[0].email='different@example.com';a.equal(assessCancellation(s,s.tickets[0]).allowed,false);const d=draftReply(s,s.tickets[0]);a.ok(!d.includes(s.orders[0].product));a.ok(!d.includes('49,000'))});
test('mismatched order cannot be manually linked',()=>a.throws(()=>run(seed(),{type:'ticket.link',id:'T-2001',orderId:'ORD-1002'}),/일치하지/));
test('active approval prevents order relinking',()=>a.throws(()=>run(req(seed()),{type:'ticket.link',id:'T-2001',orderId:''}),/승인/));
test('cannot resolve before recording a simulated answer',()=>a.throws(()=>run(seed(),{type:'ticket.resolve',id:'T-2001'}),/모의 답변/));
test('cannot resolve with an active approval even after answering',()=>a.throws(()=>run(req(reply(seed())),{type:'ticket.resolve',id:'T-2001'}),/승인/));
test('resolved inquiry can be reopened and resolved timestamp is cleared',()=>{const s=run(seed(),{type:'ticket.reopen',id:'T-2010'});a.equal(s.tickets[9].status,'open');a.equal(s.tickets[9].resolvedAt,null);parseState(s)});
test('duplicate simulated message is blocked',()=>a.throws(()=>run(reply(seed()),{type:'ticket.send',id:'T-2001'}),/중복/));
test('changed policy makes draft stale, manual editing does not bypass guard',()=>{let s=run(seed(),{type:'ticket.draft',id:'T-2001'});s=policy(s);s=run(s,{type:'ticket.draft',id:'T-2001',body:'수정한 초안'});a.throws(()=>run(s,{type:'ticket.send',id:'T-2001'}),/오래/);s=reply(s);a.equal(s.tickets[0].messages.length,1)});
test('logistics requires tracking and cannot directly cancel',()=>{a.throws(()=>run(seed(),{type:'order.logistics',id:'ORD-1001',status:'shipped',carrier:'',tracking:''},manager),/송장/);a.throws(()=>run(seed(),{type:'order.logistics',id:'ORD-1001',status:'cancelled',carrier:'',tracking:''},manager),/전환/)});
test('logistics cannot roll back shipped to preparing',()=>a.throws(()=>run(ship(seed()),{type:'order.logistics',id:'ORD-1001',status:'preparing',carrier:'x',tracking:'x'},manager),/전환/));
test('agent cannot change policy or import',()=>{a.throws(()=>run(seed(),{type:'policy.update',policy:seed().policy}),/관리자/);a.throws(()=>run(seed(),{type:'import.orders',orders:[],filename:'x.csv'}),/관리자/)});
test('scenario generation preserves old records and produces valid business cases',()=>{for(const scenario of ['shipping','cancel','race','high','mismatch']){const s=run(seed(),{type:'scenario.create',scenario});a.equal(s.orders.length,13);a.equal(s.tickets.length,13);parseState(s)}});
test('scenario prototype property is not a valid scenario',()=>a.throws(()=>run(seed(),{type:'scenario.create',scenario:'toString'}),/시나리오/));
test('300 note limit also applies to escalations',()=>{const s=seed();s.tickets[0].notes=Array.from({length:300},(_,i)=>({id:'N-'+i,body:'x',at:time,by:'x'}));a.throws(()=>run(s,{type:'ticket.escalate',id:'T-2001',reason:'인계'}),/한도/)});

test('CSV parses BOM, CRLF, commas, escaped quotes, multiline quoted fields',()=>{const rows=parseCSV('\uFEFFid,text\r\n1,"a,b"\r\n2,"say ""hi""\nnext"');a.deepEqual(rows,[['id','text'],['1','a,b'],['2','say "hi"\nnext']])});
test('CSV rejects unterminated and malformed quotes',()=>{for(const t of ['a,b\n1,"abc','a,b\n1,a"bc','a,b\n1,"a"oops'])a.throws(()=>parseCSV(t))});
test('valid order CSV produces 2 insertable rows',()=>{const p=previewCSV(sampleCSV('orders',false,time),'orders',seed(),time);a.equal(p.orders.length,2);a.equal(p.issues.filter(i=>i.severity==='error').length,0)});
test('invalid order amount is reported and preview does not mutate state',()=>{const s=seed();const p=previewCSV(sampleCSV('orders',true,time),'orders',s,time);a.ok(p.issues.some(i=>i.severity==='error'));a.equal(s.orders.length,12)});
test('duplicate required header is rejected',()=>{const p=previewCSV('id,id\nA,A','orders',seed());a.ok(p.issues.some(i=>i.message.includes('중복')))});
test('missing headers and wrong column count are rejected',()=>{a.ok(previewCSV('id\nx','orders',seed()).issues.some(i=>i.severity==='error'));const t=sampleCSV('orders',false,time).split('\r\n');t[1]+=',extra';a.ok(previewCSV(t.join('\r\n'),'orders',seed()).issues.some(i=>i.field==='열 수'))});
test('CSV duplicate IDs within file are blocked',()=>{const t=sampleCSV('orders',false,time).replace('IMPORT-102','IMPORT-101');a.ok(previewCSV(t,'orders',seed()).issues.some(i=>i.message.includes('중복')))});
test('CSV missing linked order is warning, not silent fabricated match',()=>{const p=previewCSV(sampleCSV('tickets',false,time),'tickets',seed(),time);a.equal(p.tickets.length,2);a.equal(p.issues.filter(i=>i.severity==='warning').length,2)});
test('CSV import rechecks duplicates and commits atomically',()=>{const s=seed(),o=previewCSV(sampleCSV('orders',false,time),'orders',s,time).orders;const next=run(s,{type:'import.orders',orders:o,filename:'sample.csv'},manager);a.equal(next.orders.length,14);a.throws(()=>run(next,{type:'import.orders',orders:o,filename:'sample.csv'},manager),/중복/);a.equal(next.orders.length,14);const bad=[o[0],{...o[1],amount:-1}];a.throws(()=>run(s,{type:'import.orders',orders:bad,filename:'bad.csv'},manager));a.equal(s.orders.length,12);parseState(next)});
test('order-then-ticket import correctly links uploaded records',()=>{let s=seed();s=run(s,{type:'import.orders',orders:previewCSV(sampleCSV('orders',false,time),'orders',s,time).orders,filename:'orders.csv'},manager);const p=previewCSV(sampleCSV('tickets',false,time),'tickets',s,time);a.equal(p.issues.length,0);s=run(s,{type:'import.tickets',tickets:p.tickets,filename:'tickets.csv'},manager);a.equal(s.tickets.length,14);parseState(s)});
test('CSV export mitigates common spreadsheet formula prefixes',()=>{const c=parseCSV(toCSV(['text'],[['=1+1'],[' +2'],['@sum(1)'],['-1'],['hello']]));a.equal(c[1][0],"'=1+1");a.equal(c[2][0],"' +2");a.equal(c[5][0],'hello')});
test('CSV over file limit is rejected',()=>a.throws(()=>parseCSV('x'.repeat(2000001)),/2 MB/));

test('backup round trip retains all valid records',()=>a.deepEqual(parseBackup(JSON.stringify(seed())),seed()));
test('invalid JSON, schema and nested enum are rejected',()=>{a.throws(()=>parseBackup('no'));const s=seed();s.schemaVersion=99;a.throws(()=>parseState(s));s.schemaVersion=1;s.orders[0].status='hacked';a.throws(()=>parseState(s))});
test('backup duplicates and broken approval references are rejected',()=>{let s=seed();s.orders.push(s.orders[0]);a.throws(()=>parseState(s),/중복/);s=req(seed());s.approvals[0].orderId='MISSING';a.throws(()=>parseState(s),/연결/)});
test('backup cannot claim execution without cancelled order',()=>{const s=execute(approve(req(seed())));s.orders[0].status='preparing';a.throws(()=>parseState(s),/취소 주문/)});
test('invalid calendar day and hour are rejected',()=>{a.throws(()=>iso('2026-02-30T00:00:00Z'));a.throws(()=>iso('2026-09-29T24:00:00Z'));a.equal(iso(time),time)});
test('raw backup unknown/prototype fields are discarded',()=>{const s=JSON.parse(JSON.stringify(seed()));Object.defineProperty(s,'__proto__',{value:{polluted:true},enumerable:true});s.extra='x';const clean=parseState(s);a.equal(clean.extra,undefined);a.equal(clean.polluted,undefined);a.equal({}.polluted,undefined)});
test('noninteger or nonfinite money is rejected',()=>{for(const amount of [0,-1,1.5,Infinity,NaN])a.throws(()=>parseOrder({...seed().orders[0],amount}))});

test('repository persists valid state and restores it',()=>{const storage=memory();const r=new LocalRepository(storage);a.equal(r.load().mode,'persistent');r.save(seed());a.deepEqual(new LocalRepository(storage).load().state,seed())});
test('repository session mode supports edits without browser storage',()=>{const r=new LocalRepository(null);a.equal(r.load().mode,'session');r.save(seed());a.deepEqual(r.load().state,seed())});
test('corrupt saved data is preserved and ordinary writes are blocked',()=>{const storage=memory('{broken');const r=new LocalRepository(storage);a.equal(r.load().mode,'recovery');a.throws(()=>r.save(seed()),/복구 모드/);a.equal(storage.getItem(STORAGE_KEY),'{broken');r.replace(seed());a.equal(r.load().mode,'persistent')});
test('stale repository writer detects another tab edit',()=>{const storage=memory();const one=new LocalRepository(storage),two=new LocalRepository(storage);one.load();two.load();one.save(seed());a.throws(()=>two.save(seed()),/다른 탭/)});
test('failed storage write does not destroy prior raw data',()=>{const raw=JSON.stringify(seed());const storage={getItem:()=>raw,setItem:()=>{throw Error('quota')},removeItem:()=>{}};const r=new LocalRepository(storage);r.load();a.throws(()=>r.save(run(seed(),{type:'ticket.note',id:'T-2001',body:'memo'})),/반영하지/);a.equal(r.raw(),raw)});
test('invalid replacement does not overwrite storage',()=>{const storage=memory(JSON.stringify(seed()));const r=new LocalRepository(storage);r.load();a.throws(()=>r.replace({schemaVersion:88}));a.deepEqual(JSON.parse(storage.getItem(STORAGE_KEY)),seed())});

test('dashboard metrics use actual records and handle empty state',()=>{let m=metrics(seed(),Date.parse(time));a.equal(m.total,12);a.equal(m.resolved,2);a.equal(m.resolutionRate,17);const s=seed();s.tickets=[];m=metrics(s);a.equal(m.resolutionRate,0);a.equal(m.firstReplyMinutes,null)});
test('first-response overdue stops after first answer and when resolved',()=>{const s=seed();a.equal(isOverdue(s,s.tickets[2],Date.parse(time)),true);const n=reply(s,'T-2003');a.equal(isOverdue(n,n.tickets[2],Date.parse(time)),false);a.equal(isOverdue(s,s.tickets[9],Date.parse(time)),false)});
test('chart contains seven local-calendar bins and all recent arrivals',()=>{const d=dailySeries(seed().tickets,7,new Date(time));a.equal(d.length,7);a.equal(d.reduce((n,x)=>n+x.arrived,0),12)});
// --- P0 regression: backup restore must not leak raw browser errors or damage current data when storage is full ---
function limited(limit,initial={}){const data={...initial};const used=()=>Object.entries(data).reduce((n,[k,v])=>n+k.length+v.length,0);return{data,getItem:k=>k in data?data[k]:null,setItem:(k,v)=>{const next=used()-(k in data?k.length+data[k].length:0)+k.length+v.length;if(next>limit)throw Error("Failed to execute 'setItem' on 'Storage': exceeded the quota.");data[k]=v},removeItem:k=>{delete data[k]}}}
function bigState(){const s=seed();const t=s.tickets[0];for(let i=0;i<40;i++)s.tickets.push({...t,id:`BIG-${i}`,orderId:'',status:'open',resolvedAt:null,messages:[],notes:[],draft:'d'.repeat(4000)});return s}
test('restore over storage quota shows a Korean message, not the raw browser error, and keeps current data',()=>{const cur=JSON.stringify(seed());const storage=limited(cur.length+STORAGE_KEY.length+2000,{[STORAGE_KEY]:cur});const r=new LocalRepository(storage);r.load();a.throws(()=>r.replace(bigState()),e=>{a.match(e.message,/복원할 자료가 브라우저 저장 용량/);a.match(e.message,/현재 자료는 바뀌지 않았습니다/);a.doesNotMatch(e.message,/Failed to execute|quota/);return true});a.equal(storage.getItem(STORAGE_KEY),cur);a.deepEqual(new LocalRepository(storage).load().state,seed())});
test('failed restore leaves the repository usable: normal saves still work afterwards',()=>{const cur=JSON.stringify(seed());const storage=limited(cur.length+STORAGE_KEY.length+2000,{[STORAGE_KEY]:cur});const r=new LocalRepository(storage);r.load();a.throws(()=>r.replace(bigState()),/복원할 자료/);const next=run(seed(),{type:'ticket.note',id:'T-2001',body:'복원 실패 뒤 메모'});r.save(next);a.equal(new LocalRepository(storage).load().state.tickets[0].notes.length,1)});
test('failed restore in recovery mode preserves the unreadable original and stays in recovery',()=>{const storage=limited(3000,{[STORAGE_KEY]:'{broken'});const r=new LocalRepository(storage);a.equal(r.load().mode,'recovery');a.throws(()=>r.replace(bigState()),/복원할 자료/);a.equal(storage.getItem(STORAGE_KEY),'{broken');a.throws(()=>r.save(seed()),/복구 모드/)});
test('restore write failure that clobbers the value is rolled back to the previous raw data',()=>{const cur=JSON.stringify(seed());const data={[STORAGE_KEY]:cur};const storage={getItem:k=>data[k]??null,setItem:(k,v)=>{if(v!==cur&&k===STORAGE_KEY&&v.length>1000&&v.length!==cur.length){data[k]=v.slice(0,20);throw Error('quota')}data[k]=v},removeItem:k=>{delete data[k]}};const r=new LocalRepository(storage);r.load();a.throws(()=>r.replace(bigState()),/복원할 자료/);a.equal(data[STORAGE_KEY],cur)});
test('restore write failure with no previous data leaves storage empty',()=>{const data={};const storage={getItem:k=>data[k]??null,setItem:(k,v)=>{data[k]=v.slice(0,5);throw Error('quota')},removeItem:k=>{delete data[k]}};const r=new LocalRepository(storage);r.load();a.throws(()=>r.replace(seed()),/복원할 자료/);a.equal(data[STORAGE_KEY],undefined)});
test('successful restore still replaces data, clears recovery mode and reports persistent storage',()=>{const storage=limited(1e7,{[STORAGE_KEY]:'{broken'});const r=new LocalRepository(storage);r.load();r.replace(seed());a.equal(r.load().mode,'persistent');a.deepEqual(new LocalRepository(storage).load().state,seed())});
test('fits() pre-flight predicts storage capacity without touching the saved state or leaving probe keys',()=>{const cur=JSON.stringify(seed());const storage=limited(cur.length+STORAGE_KEY.length+2000,{[STORAGE_KEY]:cur});const r=new LocalRepository(storage);r.load();a.equal(r.fits(seed()),true);a.equal(r.fits(bigState()),false);a.deepEqual(Object.keys(storage.data),[STORAGE_KEY]);a.equal(storage.data[STORAGE_KEY],cur)});
test('fits() agrees with replace(): a state that fits restores, a state that does not fails and keeps data',()=>{const cur=JSON.stringify(seed());const small=seed();small.tickets=small.tickets.slice(0,3);small.approvals=[];const storage=limited(cur.length+STORAGE_KEY.length+500,{[STORAGE_KEY]:cur});const r=new LocalRepository(storage);r.load();const big=bigState();a.equal(r.fits(small),true);r.replace(small);a.equal(new LocalRepository(storage).load().state.tickets.length,3);const r2=new LocalRepository(storage);r2.load();a.equal(r2.fits(big),false);const before=storage.getItem(STORAGE_KEY);a.throws(()=>r2.replace(big),/복원할 자료/);a.equal(storage.getItem(STORAGE_KEY),before)});
test('fits() is true in session mode (no browser storage) and false when storage cannot be read',()=>{a.equal(new LocalRepository(null).fits(bigState()),true);const broken={getItem:()=>{throw Error('denied')},setItem:()=>{throw Error('denied')},removeItem:()=>{}};a.equal(new LocalRepository(broken).fits(seed()),false)});
test('save failure and restore failure messages stay distinct but both promise existing data is kept',()=>{const {SAVE_FAILED,RESTORE_FAILED}=require('../.test-build/src/lib/repository.js');a.notEqual(SAVE_FAILED,RESTORE_FAILED);a.match(SAVE_FAILED,/기존 자료는 유지/);a.match(RESTORE_FAILED,/현재 자료는 바뀌지 않았습니다/)});
