import React from 'react';
import { useData } from '../store';
import { Button, Badge, Icon, PageHeading, Status, Help, Empty } from '../components/ui';
import { metrics, dailySeries } from '../domain/metrics';
import { ticketLabels, typeLabels } from '../domain/types';
import { isOverdue } from '../domain/rules';
import { time } from '../lib/files';
export function Dashboard() {
    const { state, go, now } = useData();
    const m = metrics(state, now);
    const series = dailySeries(state.tickets);
    const max = Math.max(2, ...series.flatMap(s => [s.arrived, s.resolved]));
    const urgent = state.tickets.filter(t => t.status !== 'resolved').sort((a, b) => Number(isOverdue(state, b, now)) - Number(isOverdue(state, a, now)) || Number(b.priority === 'high') - Number(a.priority === 'high')).slice(0, 5);
    const categories = Object.entries(typeLabels).map(([type, label]) => ({ type, label, count: state.tickets.filter(t => t.type === type).length }));
    return <>
 <PageHeading eyebrow="YOUR SUPPORT OPERATIONS" title="오늘의 고객지원, 한눈에." description="문의가 들어온 순간부터 해결될 때까지, 모든 숫자는 실제 실습 기록에서 계산됩니다." actions={<><Button icon="upload" onClick={() => go('import')}>자료 가져오기</Button><Button variant="primary" icon="plus" onClick={() => go('tickets')}>문의 작업대</Button></>}/>
 <section className="welcome-banner"><div><Badge tone="mint">BUILD BY UNDERSTANDING</Badge><h2>읽는 것보다,<br />한 건을 직접 처리해 보세요.</h2><p>주문을 확인하고, 답변을 작성하고, 취소를 승인하는 과정.<br />버튼 하나가 어떤 데이터를 바꾸는지 연결해서 배웁니다.</p><Button variant="primary" icon="arrow" onClick={() => go('tickets', state.tickets.find(t => t.type === 'cancellation' && t.status === 'open')?.id)}>첫 문의 처리하기</Button></div><div className="flow-visual" aria-label="문의 접수, 판단, 승인, 결과 확인"><div className="flow-node"><span><Icon name="inbox"/></span><div><small>01 · INPUT</small><strong>문의 접수</strong></div><Badge tone="teal">실제 입력</Badge></div><div className="flow-connector"/><div className="flow-node emphasis"><span><Icon name="shield"/></span><div><small>02 · DECISION</small><strong>정책 확인 & 승인</strong></div><Icon name="check"/></div><div className="flow-connector"/><div className="flow-node"><span><Icon name="chart"/></span><div><small>03 · OUTPUT</small><strong>처리 결과 · 이력</strong></div><Badge tone="teal">연결된 기록</Badge></div></div></section>
 <section className="kpi-grid">{[{ label: '미해결 문의', value: m.open, suffix: '건', hint: `전체 ${m.total}건 중 해결 전`, icon: 'inbox', tone: 'blue', page: 'tickets' as const }, { label: '승인 · 실행 대기', value: m.pending + m.approved, suffix: '건', hint: `검토 ${m.pending} · 실행 전 ${m.approved}`, icon: 'shield', tone: 'amber', page: 'approvals' as const }, { label: '첫 응답 목표 초과', value: m.overdue, suffix: '건', hint: `${state.policy.slaHours}시간 초과 · 무응답 문의`, icon: 'clock', tone: 'red', page: 'tickets' as const }, { label: '문의 해결 비율', value: m.resolutionRate, suffix: '%', hint: `해결 ${m.resolved} / 전체 ${m.total}`, icon: 'check', tone: 'teal', page: 'reports' as const }].map(k => <button className="kpi-card" key={k.label} onClick={() => go(k.page)}><div><span>{k.label}</span><span className={`kpi-icon ${k.tone}`}><Icon name={k.icon} size={18}/></span></div><strong>{k.value}<small>{k.suffix}</small></strong><p>{k.hint}<Icon name="arrow" size={15}/></p></button>)}</section>
 <div className="dashboard-grid"><section className="panel chart-panel"><div className="panel-heading"><div><h2>문의의 흐름</h2><p>최근 7일 · 브라우저 현지 날짜 기준</p></div><div className="legend"><span><i className="teal-dot"/>접수</span><span><i className="light-dot"/>해결</span></div></div><div className="bar-chart" role="img" aria-label={series.map(x => `${x.label} 접수 ${x.arrived}건 해결 ${x.resolved}건`).join(', ')}>{series.map(x => <div className="bar-group" key={x.key}><div className="bars"><div className="bar arrived" style={{ height: `${x.arrived / max * 100}%` }} title={`접수 ${x.arrived}건`}><span>{x.arrived || ''}</span></div><div className="bar resolved" style={{ height: `${x.resolved / max * 100}%` }} title={`해결 ${x.resolved}건`}><span>{x.resolved || ''}</span></div></div><small>{x.label}</small></div>)}</div><div className="chart-caption">접수일과 해결일을 각각 집계합니다. 모의 답변도 실습 기록에 포함됩니다.</div></section>
 <section className="panel mix-panel"><div className="panel-heading"><div><h2>문의 유형</h2><p>어떤 문제가 반복될까요?</p></div><Icon name="inbox"/></div><div className="category-total"><strong>{m.total}</strong><span>전체 문의</span></div>{categories.map((x, i) => <div className="category-row" key={x.type}><span><i className={`category-dot c${i}`}/>{x.label}</span><strong>{x.count}<small>건</small></strong><div className="progress-track"><i style={{ width: `${m.total ? x.count / m.total * 100 : 0}%` }}/></div></div>)}</section></div>
 <div className="dashboard-bottom"><section className="panel"><div className="panel-heading"><div><h2>먼저 확인할 문의</h2><p>첫 응답 지연 → 높은 우선순위 순</p></div><Button variant="ghost" icon="arrow" onClick={() => go('tickets')}>전체 보기</Button></div>{urgent.length ? <div className="compact-tickets">{urgent.map(t => <button key={t.id} onClick={() => go('tickets', t.id)}><span className="avatar">{t.customer[0]}</span><div><strong>{t.subject}</strong><small>{t.customer} · {typeLabels[t.type]}</small></div>{isOverdue(state, t, now) ? <Badge tone="red">응답 지연</Badge> : <Status status={t.status} label={ticketLabels[t.status]}/>}<Icon name="chevron" size={16}/></button>)}</div> : <Empty title="미해결 문의가 없습니다" description="새 문의를 접수하거나 자료를 가져와 다음 실습을 시작하세요."/>}</section>
 <section className="learning-card"><span className="eyebrow">LEARNING PATH</span><h2>화면 너머의<br />업무를 이해하세요.</h2><p>왜 승인과 실행을 나눌까요?<br />주문 자료가 바뀌면 어떻게 될까요?</p><div className="learning-stat"><strong>{state.lessons.length}</strong><span>/ 6 개념 체크</span></div><Button icon="arrow" onClick={() => go('learn')}>단계별 학습 가이드</Button><small>수료 여부는 직접 체크하는 학습 기록입니다.</small></section></div>
 <Help title="이 화면은 무엇을 알려주나요?">미해결 건수가 늘면 처리할 일이 쌓이고, 무응답 시간이 길어지면 우선 대응이 필요합니다. 현재 데이터는 {state.sourceLabel}이며 기준 시점은 {time(state.sourceAt)}입니다. 실제 고객지원 실적이나 AI 정확도를 뜻하지 않습니다.</Help>
 </>;
}
