import React, { useState } from 'react';
import { useData } from '../store';
import { Button, Badge, Icon, PageHeading, Help } from '../components/ui';
export const scenarios = [
    { id: 'shipping', n: '01', title: '배송 문의를 끝까지 처리하기', concept: '정보를 읽는 일과 실제 메시지를 보내는 일은 다릅니다.', steps: ['연습 자료를 만들고 연결된 주문 상태·송장번호를 확인합니다.', '규칙 기반 초안을 생성하고 어떤 자료가 사용되었는지 읽습니다.', '모의 답변을 기록한 뒤 해결 처리합니다. 리포트의 변화를 확인합니다.'], question: '모의 답변을 기록하면 실제 고객에게 메시지가 갈까요?', answer: '아니요. 이 앱의 발신함과 이력에만 저장됩니다. 실제 발송은 별도의 서버·메시지 공급자 연동이 필요합니다.' },
    { id: 'cancel', n: '02', title: '취소 요청 → 승인 → 모의 실행', concept: '판단, 승인, 실행을 분리해 잘못된 작업을 줄입니다.', steps: ['준비 중인 주문의 취소 문의를 만듭니다. 판단 근거 5개를 확인합니다.', '취소 승인 요청을 등록하고 상단 역할을 관리자로 전환합니다.', '승인함에서 검토 승인 후, 별도로 재검사·모의 실행합니다.', '문의로 돌아와 새 초안을 생성하고 결과를 기록한 뒤 해결합니다.'], question: '검토 승인만 누르면 주문 상태가 취소 완료로 바뀔까요?', answer: '아니요. 승인 상태는 실행 전입니다. 별도 실행에서 최신 조건을 재검사한 후 로컬 주문 상태만 바뀝니다. 실제 환불은 없습니다.' },
    { id: 'race', n: '03', title: '승인 뒤 출고되는 예외 체험', concept: '요청 시점의 데이터가 실행 시점에도 같다는 보장은 없습니다.', steps: ['준비 중 주문의 취소를 요청하고 관리자 역할로 검토 승인합니다.', '실행하기 전 주문 관리에서 해당 주문을 배송 중으로 바꿉니다. 송장번호를 입력하세요.', '승인함에서 재검사 후 모의 실행을 누릅니다. ‘차단’ 이력을 확인합니다.'], question: '이미 승인했는데 왜 실행이 차단될까요?', answer: '주문의 버전과 출고 상태가 바뀌었기 때문입니다. 과거 승인을 그대로 믿지 않고 현재 상태를 다시 검사합니다. 이를 상용 서비스에서는 서버 트랜잭션과 동시성 제어로 강화해야 합니다.' },
    { id: 'high', n: '04', title: '고액 주문의 처리 범위 정하기', concept: '자동 처리하지 않을 경계를 정하는 것도 제품 설계입니다.', steps: ['취소 검토 한도를 넘는 고액 주문을 만듭니다.', '판단 근거의 금액 검사를 보고 취소 승인 요청이 제한되는지 확인합니다.', '담당자 인계 사유와 내부 메모를 남깁니다. 필요하면 관리자 정책을 변경하고 재검사합니다.'], question: '조건을 만족하지 않는 요청을 조용히 무시하면 될까요?', answer: '아니요. 무엇이 부족한지 보여주고 담당자 인계·추가 확인 경로를 제공해야 합니다. 한도는 학습용 운영 규칙이며 소비자 권리를 판단하는 법률 규정이 아닙니다.' },
    { id: 'mismatch', n: '05', title: '문의자와 주문자가 다를 때', concept: '주문번호 하나만 아는 것은 고객 본인 확인과 다릅니다.', steps: ['문의자 이메일과 주문자 이메일이 다른 자료를 만듭니다.', '판단 근거에서 불일치를 확인하고 답변 초안을 생성합니다.', '민감한 주문 정보를 답변에 넣지 않는지 확인한 후 담당자에게 인계합니다.'], question: '이메일 문자열이 같으면 완전한 본인 인증일까요?', answer: '아니요. 여기서는 일치 비교만 합니다. 실제 서비스에는 인증된 세션, 접근 권한, 안전한 본인 확인 과정이 필요합니다.' },
    { id: 'data', n: '06', title: '파일 오류와 백업 복원 배우기', concept: '화면보다 데이터의 출처와 보존 방식이 중요합니다.', steps: ['자료 가져오기에서 오류 샘플을 내려받아 검사합니다. 오류가 있으면 전체 반영이 막힙니다.', '정상 주문 CSV를 먼저, 문의 CSV를 다음으로 반영합니다.', '설정에서 전체 JSON을 백업하고 복원 미리보기를 확인합니다. 개인 자료는 GitHub에 올리지 않습니다.'], question: 'HTML 소스만 다른 컴퓨터로 옮기면 내가 입력한 자료도 따라갈까요?', answer: '아니요. 프로그램 소스와 브라우저에 저장한 작업 자료는 별개입니다. JSON 백업을 별도로 옮겨 복원해야 합니다.' }
];
export function Learn() { const { state, run, go } = useData(); const [answer, setAnswer] = useState<string | null>(null); return <><PageHeading eyebrow="LEARN THE BUSINESS, NOT JUST THE BUTTONS" title="한 건씩 배우는 실습 가이드" description="설명 → 조작 → 예외 확인 → 내 말로 설명하기. 완료는 직접 체크하는 학습 기록입니다." actions={<Badge tone="teal">{state.lessons.length} / 6 개념 체크</Badge>}/><section className="learning-intro"><div><Icon name="learn" size={32}/><h2>이 앱으로 배우는 사업</h2><p>고객은 쇼핑몰 운영자입니다. 반복 문의를 줄이면서도 잘못된 취소와 안내를 막아야 합니다. 비용을 내는 이유는 ‘예쁜 대시보드’가 아니라, 업무가 빠짐없이 처리되는 데 있습니다.</p></div><div><span>INPUT</span><strong>주문 · 문의 · 정책</strong><Icon name="arrow"/><span>PROCESS</span><strong>판단 · 승인 · 기록</strong><Icon name="arrow"/><span>OUTPUT</span><strong>답변 · 상태 · 이력</strong></div></section><div className="learning-scenarios">{scenarios.map(s => <article className={`panel scenario ${state.lessons.includes(s.id) ? 'complete' : ''}`} key={s.id}><div className="scenario-heading"><span>{s.n}</span><div><h2>{s.title}</h2><p>{s.concept}</p></div><label className="check-label"><input type="checkbox" checked={state.lessons.includes(s.id)} onChange={() => run({ type: 'lesson.toggle', id: s.id })}/>이해했어요</label></div><ol>{s.steps.map(step => <li key={step}>{step}</li>)}</ol><div className="scenario-actions">{s.id === 'data' ? <Button variant="primary" icon="upload" onClick={() => go('import')}>자료 가져오기 실습</Button> : <Button variant="primary" icon="plus" onClick={() => { if (run({ type: 'scenario.create', scenario: s.id as 'shipping' | 'cancel' | 'race' | 'high' | 'mismatch' }))
    go('tickets'); }}>이 상황의 새 연습 자료 만들기</Button>}<Button onClick={() => setAnswer(answer === s.id ? null : s.id)}>이해 확인 질문</Button></div>{answer === s.id && <div className="quiz"><strong>Q. {s.question}</strong><details><summary>설명 확인</summary><p>{s.answer}</p></details></div>}</article>)}</div><Help title="학습을 마친 뒤 AI에게 이렇게 설명해 보세요">“내가 이해한 취소 업무는 … 입니다. 데이터가 달라지면 … 를 다시 확인해야 합니다.” 코드를 전부 외우기보다, 무엇을 입력받고 어떤 조건에서 처리하는지 설명할 수 있으면 됩니다.</Help></>; }
