import React, { useEffect, useState } from 'react';
import { useData } from '../store';
import { Button, Badge, Icon, PageHeading, Status, Help, Empty, Modal, Field } from '../components/ui';
import { Ticket, TicketInput, TicketStatus, TicketType, Priority, ticketLabels, typeLabels, orderLabels, approvalLabels } from '../domain/types';
import { assessCancellation, fingerprint, isOverdue, linkedOrder } from '../domain/rules';
import { copyText, download, money, shortId, time } from '../lib/files';
export function Tickets() {
    const { state, selectedId, select, query, setQuery, now } = useData();
    const [filter, setFilter] = useState('all');
    const [type, setType] = useState('all');
    const [showNew, setShowNew] = useState(false);
    const matched = state.tickets.filter(t => (filter === 'all' || filter === 'unresolved' && t.status !== 'resolved' || filter === 'overdue' && isOverdue(state, t, now) || t.status === filter) && (type === 'all' || t.type === type) && [t.id, t.customer, t.email, t.subject, t.orderId, t.body].join(' ').toLowerCase().includes(query.toLowerCase()));
    const selected = matched.find(t => t.id === selectedId) ?? matched[0];
    return <>
 <PageHeading eyebrow="SUPPORT WORKBENCH" title="문의 작업대" description="접수 → 주문 연결 → 판단 → 답변 → 해결. 한 문의를 끝까지 처리해 보세요." actions={<Button variant="primary" icon="plus" onClick={() => { setFilter('all'); setType('all'); setQuery(''); setShowNew(true); }}>새 문의 접수</Button>}/>
 <Help title="취소 요청을 골라 시작해 보세요">‘규칙 기반 초안 생성’은 주문과 정책을 읽어 문장을 조합합니다. AI 호출은 없습니다. 취소 요청은 승인함을 거쳐야 하며, ‘모의 답변 기록’은 고객에게 실제로 발송되지 않습니다.</Help>
 <div className="workbench"><section className="ticket-list panel"><div className="list-tools"><div className="input-icon"><Icon name="search" size={17}/><input aria-label="문의 목록 검색" placeholder="고객 · 제목 · 주문번호" value={query} onChange={e => setQuery(e.target.value)}/></div><div className="filter-row"><select aria-label="문의 상태 필터" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">전체 상태</option><option value="unresolved">미해결 전체</option><option value="overdue">응답 지연</option>{Object.entries(ticketLabels).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select><select aria-label="문의 유형 필터" value={type} onChange={e => setType(e.target.value)}><option value="all">전체 유형</option>{Object.entries(typeLabels).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></div><small>{matched.length}건 검색됨 · 최대 2,000개 실습</small></div><div className="ticket-scroll">{matched.length ? matched.map(t => <button className={`ticket-item ${selected?.id === t.id ? 'selected' : ''}`} key={t.id} onClick={() => select(t.id)}><div><span className="avatar small">{t.customer[0]}</span><strong>{t.customer}</strong><small>{time(t.createdAt)}</small></div><h3>{t.subject}</h3><p>{t.body.replace(/\n/g, ' ')}</p><footer><Status status={t.status} label={ticketLabels[t.status]}/><span>{isOverdue(state, t, now) ? <Badge tone="red">지연</Badge> : t.priority === 'high' ? <Badge tone="amber">높음</Badge> : typeLabels[t.type]}</span></footer></button>) : <Empty title="일치하는 문의가 없습니다"/>}</div></section>
 <section className="ticket-detail panel">{selected ? <TicketDetail ticket={selected} key={selected.id}/> : <Empty title="왼쪽에서 문의를 선택하세요"/>}</section></div>{showNew && <NewTicket onClose={() => setShowNew(false)}/>}</>;
}
function NewTicket({ onClose }: {
    onClose: () => void;
}) { const { run, state, select } = useData(); const [input, setInput] = useState<TicketInput>({ customer: '', email: '', subject: '', body: '', orderId: '', type: 'shipping', priority: 'normal', assignee: '상담원 지수' }); function change(key: keyof TicketInput, v: string) { setInput({ ...input, [key]: v }); } return <Modal title="가상 문의 접수" onClose={onClose}><form onSubmit={e => { e.preventDefault(); if (run({ type: 'ticket.create', input })) {
    onClose();
} }}><div className="notice"><Icon name="info"/>실제 고객 개인정보 대신 example.com 주소와 가상 이름을 사용하세요.</div><div className="form-grid"><Field label="고객명"><input required maxLength={80} value={input.customer} onChange={e => change('customer', e.target.value)} placeholder="가상 고객"/></Field><Field label="이메일"><input required type="email" maxLength={254} value={input.email} onChange={e => change('email', e.target.value)} placeholder="demo1@example.com"/></Field></div><Field label="문의 제목"><input required maxLength={180} value={input.subject} onChange={e => change('subject', e.target.value)}/></Field><Field label="문의 내용"><textarea required rows={4} maxLength={6000} value={input.body} onChange={e => change('body', e.target.value)}/></Field><div className="form-grid"><Field label="주문번호" hint="없는 주문번호도 접수할 수 있지만 취소 판단은 차단됩니다."><input list="order-list" value={input.orderId} maxLength={100} onChange={e => change('orderId', e.target.value)} placeholder="ORD-1001"/><datalist id="order-list">{state.orders.map(o => <option key={o.id} value={o.id}>{o.customer}</option>)}</datalist></Field><Field label="문의 유형"><select value={input.type} onChange={e => change('type', e.target.value)}>{Object.entries(typeLabels).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></Field><Field label="우선순위"><select value={input.priority} onChange={e => change('priority', e.target.value)}><option value="low">낮음</option><option value="normal">보통</option><option value="high">높음</option></select></Field><Field label="담당자"><select value={input.assignee} onChange={e => change('assignee', e.target.value)}><option>상담원 지수</option><option>상담원 민지</option><option>관리자</option></select></Field></div><div className="modal-actions"><Button onClick={onClose}>취소</Button><Button type="submit" variant="primary">문의 접수</Button></div></form></Modal>; }
function TicketDetail({ ticket: t }: {
    ticket: Ticket;
}) {
    const { state, run, go, notify } = useData();
    const [draft, setDraft] = useState(t.draft);
    const [note, setNote] = useState('');
    const [tab, setTab] = useState('conversation');
    const [request, setRequest] = useState(false);
    const [escalate, setEscalate] = useState(false);
    const [reason, setReason] = useState('');
    const [link, setLink] = useState(t.orderId);
    useEffect(() => { setDraft(t.draft); }, [t.draft]);
    useEffect(() => setLink(t.orderId), [t.orderId]);
    const order = linkedOrder(state, t);
    const evaluation = assessCancellation(state, t);
    const stale = !!t.draftFingerprint && t.draftFingerprint !== fingerprint(state, t);
    const requests = state.approvals.filter(a => a.ticketId === t.id);
    const active = requests.some(a => ['pending', 'approved'].includes(a.status));
    const last = requests[0];
    const history = state.events.filter(e => e.entityId === t.id || requests.some(a => a.id === e.entityId));
    const closed = t.status === 'resolved';
    function recordReply() { if (draft !== t.draft && !run({ type: 'ticket.draft', id: t.id, body: draft }))
        return; run({ type: 'ticket.send', id: t.id }); }
    return <><div className="detail-heading"><div className="eyebrow">{shortId(t.id)} <span>· {typeLabels[t.type]}</span></div><h2>{t.subject}</h2><div className="detail-meta"><span><Icon name="user" size={15}/>{t.customer}</span><span>{t.email}</span><Status status={t.status} label={ticketLabels[t.status]}/></div><div className="detail-controls"><label>담당자<select aria-label="담당자 변경" value={t.assignee} onChange={e => run({ type: 'ticket.meta', id: t.id, priority: t.priority, assignee: e.target.value })}>{['상담원 지수', '상담원 민지', '관리자', ...(!['상담원 지수', '상담원 민지', '관리자'].includes(t.assignee) ? [t.assignee] : [])].map(n => <option key={n}>{n}</option>)}</select></label><label>우선순위<select aria-label="우선순위 변경" value={t.priority} onChange={e => run({ type: 'ticket.meta', id: t.id, priority: e.target.value as Priority, assignee: t.assignee })}><option value="low">낮음</option><option value="normal">보통</option><option value="high">높음</option></select></label>{closed ? <Button icon="refresh" onClick={() => run({ type: 'ticket.reopen', id: t.id })}>다시 열기</Button> : <Button icon="check" disabled={active || !t.messages.length} title={active ? '승인 절차를 먼저 마무리하세요' : !t.messages.length ? '모의 답변을 먼저 기록하세요' : '문의 해결 상태로 변경'} onClick={() => run({ type: 'ticket.resolve', id: t.id })}>해결 처리</Button>}</div></div>
 <div className="detail-tabs" role="tablist" aria-label="문의 상세">{[['conversation', '대화 · 답변'], ['rules', '판단 근거'], ['history', `처리 이력 ${history.length}`]].map(([v, l]) => <button key={v} role="tab" aria-selected={tab === v} onClick={() => setTab(v)}>{l}</button>)}</div>
 <div className="detail-body">{tab === 'conversation' ? <>
 <div className="order-link-box"><div className="section-caption"><span><Icon name="box" size={17}/>연결 주문</span>{order && <Status status={order.status} label={orderLabels[order.status]}/>}</div>{order ? <div className="order-summary"><strong>{order.product}</strong><span>{order.id} · {money(order.amount)}</span><small>주문 v{order.version} · 자료 갱신 {time(order.updatedAt)}</small></div> : <p className="muted">주문 자료가 연결되지 않았습니다.</p>}{order && order.email !== t.email && <p className="text-danger">문의자와 주문자 이메일이 다릅니다. 주문 안내/취소가 제한됩니다.</p>}<div className="inline-form"><select aria-label="연결할 주문" value={link} onChange={e => setLink(e.target.value)}><option value="">연결 없음</option>{!state.orders.some(o => o.id === link) && link && <option value={link}>{link} · 자료 없음</option>}{state.orders.map(o => <option key={o.id} value={o.id}>{o.id} · {o.customer}</option>)}</select><Button disabled={closed || active || link === t.orderId} onClick={() => run({ type: 'ticket.link', id: t.id, orderId: link })}>연결 변경</Button></div></div>
 <div className="message customer-message"><div><span className="avatar small">{t.customer[0]}</span><strong>고객의 문의</strong><small>{time(t.createdAt)}</small></div><p>{t.body}</p></div>{t.messages.map(m => <div className="message outgoing" key={m.id}><div><Badge tone="teal">모의 답변</Badge><strong>{m.by}</strong><small>{time(m.at)}</small></div><p>{m.body}</p></div>)}
 {last && <div className="approval-inline"><Icon name="shield"/><div><strong>취소 요청: {approvalLabels[last.status]}</strong><p>{last.status === 'executed' ? '주문은 모의 취소되었지만 고객 안내와 해결 처리는 별도입니다.' : '승인 상태와 실행 상태를 구분하여 확인하세요.'}</p></div><Button onClick={() => go('approvals')}>승인함</Button></div>}
 {!closed && <section className="composer"><div className="section-caption"><span><Icon name="mail" size={17}/>답변 작성</span><Badge tone="neutral">규칙 기반 · AI 미연결</Badge></div><Button icon="spark" onClick={() => run({ type: 'ticket.draft', id: t.id })}>규칙 기반 초안 생성</Button>{stale && <div className="notice red"><Icon name="warning"/>주문/정책이 달라졌습니다. 오래된 초안은 발송 기록할 수 없습니다. 다시 생성하세요.</div>}<textarea aria-label="답변 초안" rows={7} placeholder="초안을 생성하거나 직접 입력하세요. 내용을 확인한 뒤 모의 답변으로 기록합니다." value={draft} onChange={e => setDraft(e.target.value)} maxLength={6000}/><small className="muted">{draft.length}/6,000자 · ‘기록’은 로컬 보관이며 실제 메시지 발송이 아닙니다.</small><div className="composer-actions"><Button disabled={!draft.trim()} onClick={() => run({ type: 'ticket.draft', id: t.id, body: draft })}>초안 저장</Button><Button icon="copy" disabled={!draft.trim()} onClick={async () => { if (await copyText(draft))
            notify('답변을 복사했습니다.');
        else {
            download(`${t.id}-reply.txt`, draft);
            notify('클립보드를 사용할 수 없어 TXT로 내보냈습니다.');
        } }}>복사</Button><Button variant="primary" icon="send" disabled={!draft.trim() || stale} onClick={recordReply}>모의 답변 기록</Button></div></section>}
 <div className="action-row">{t.type === 'cancellation' && <Button variant="primary" icon="shield" disabled={closed || active || !evaluation.allowed || state.approvals.some(a => a.orderId === t.orderId && ['pending', 'approved'].includes(a.status))} onClick={() => { setReason(t.body); setRequest(true); }}>취소 승인 요청</Button>}<Button disabled={closed || active} onClick={() => { setReason(''); setEscalate(true); }}>담당자에게 인계</Button><Button variant="ghost" onClick={() => setTab('rules')}>판단 근거 보기</Button></div>
 <section className="notes"><h3>내부 메모 <small>고객에게 보내지 않는 기록</small></h3>{t.notes.map(n => <div className="note" key={n.id}><strong>{n.by}<small>{time(n.at)}</small></strong><p>{n.body}</p></div>)}<div className="inline-form"><input aria-label="내부 메모" placeholder="다음 담당자에게 전달할 내용" value={note} maxLength={2000} onChange={e => setNote(e.target.value)}/><Button disabled={!note.trim()} onClick={() => { if (run({ type: 'ticket.note', id: t.id, body: note }))
            setNote(''); }}>메모 추가</Button></div></section>
 </> : tab === 'rules' ? <><div className="rule-intro"><Icon name="shield" size={28}/><h3>{evaluation.title}</h3><p>아래는 ‘출고 전 취소’ 전용 검사입니다. 학습용 정책이며 실제 법률·환불 규정을 대신하지 않습니다.</p></div>{evaluation.checks.map(c => <div className={`rule-check ${c.pass ? 'pass' : 'fail'}`} key={c.label}><span><Icon name={c.pass ? 'check' : 'x'} size={18}/></span><div><strong>{c.label}</strong><p>{c.detail}</p></div></div>)}<div className="notice"><Icon name="info"/>조건을 충족해도 자동 취소하지 않습니다. 승인 시와 실행 직전에 주문 버전·정책 버전을 다시 검사합니다.</div><Button onClick={() => go('policies')}>학습 정책 확인</Button></> : <>{history.length ? history.map(e => <div className="timeline-event" key={e.id}><i /><div><small>{time(e.at)} · {e.actor}</small><strong>{e.detail}</strong><code>{e.kind}</code></div></div>) : <Empty title="아직 처리 이력이 없습니다" description="초안을 만들거나 메모를 추가하면 첫 이력이 쌓입니다."/>}</>}
 </div>{(request || escalate) && <Modal title={request ? '취소 승인 요청' : '담당자 인계'} onClose={() => { setRequest(false); setEscalate(false); }}><form onSubmit={e => { e.preventDefault(); const ok = request ? run({ type: 'approval.request', ticketId: t.id, reason }) : run({ type: 'ticket.escalate', id: t.id, reason }); if (ok) {
        setRequest(false);
        setEscalate(false);
    } }}><div className="notice"><Icon name="info"/>{request ? '요청만 등록합니다. 실제 취소/환불은 하지 않으며 관리자 역할의 검토가 필요합니다.' : '이 앱의 처리 범위 밖이거나 추가 확인이 필요한 이유를 기록합니다.'}</div><Field label="사유"><textarea required rows={4} value={reason} maxLength={1500} onChange={e => setReason(e.target.value)}/></Field><div className="modal-actions"><Button onClick={() => { setRequest(false); setEscalate(false); }}>돌아가기</Button><Button type="submit" variant="primary">{request ? '승인 요청 등록' : '인계 기록'}</Button></div></form></Modal>}</>;
}
